f = open('backend/app/main.py', 'r', encoding='utf-8')
c = f.read()
f.close()
c = c.replace('C:/tradingIA/html/index.html', 'html/index.html')
c = c.replace('C:/tradingIA/html/agent.html', 'html/agent.html')
c = c.replace('C:/tradingIA/agent_state.json', 'agent_state.json')
f = open('backend/app/main.py', 'w', encoding='utf-8')
f.write(c)
f.close()
print('OK - chemins corriges')